#!/usr/bin/env python3
"""Build the idempotent public seed migration for the owner's requested games."""

from __future__ import annotations

import argparse
import json
import unicodedata
import uuid
from pathlib import Path
from typing import Any


SEED_NAMESPACE = uuid.UUID("607c881d-8407-5f70-a847-a5c07ed1d699")
FORBIDDEN_KEYS = {
    "purchasePrice", "basePrice", "componentPrice", "extraComponentsPrice",
    "organizerPrice", "memo", "reviewMemo", "localPath", "imageRef",
    "ownerId", "ownerUserId", "personalRating", "listPriceWon", "priceKind",
}


def submission_id_for(requested_name: str) -> str:
    canonical = unicodedata.normalize("NFKC", requested_name).casefold().strip()
    if not canonical:
        raise ValueError("requestedName must not be blank")
    return str(uuid.uuid5(SEED_NAMESPACE, canonical))


def _walk_keys(value: Any):
    if isinstance(value, dict):
        for key, child in value.items():
            yield key
            yield from _walk_keys(child)
    elif isinstance(value, list):
        for child in value:
            yield from _walk_keys(child)


def load_requested_games(path: Path) -> list[dict[str, Any]]:
    document = json.loads(path.read_text(encoding="utf-8"))
    requests = document.get("requests")
    if not isinstance(requests, list):
        raise ValueError("requests must be an array")

    games: list[dict[str, Any]] = []
    for row in requests:
        if not isinstance(row, dict) or row.get("resolution") != "ADD_PENDING":
            continue
        requested_name = row.get("requestedName")
        submission = row.get("submission")
        if not isinstance(requested_name, str) or not isinstance(submission, dict):
            raise ValueError("ADD_PENDING rows require requestedName and submission")
        forbidden = FORBIDDEN_KEYS.intersection(_walk_keys(submission))
        if forbidden:
            raise ValueError(f"forbidden public fields: {sorted(forbidden)}")
        games.append({
            "requestedName": requested_name,
            "submissionId": submission_id_for(requested_name),
            "publicGame": submission,
        })

    ids = [game["submissionId"] for game in games]
    if len(ids) != len(set(ids)):
        raise ValueError("generated submission IDs must be unique")
    return games


def _json(value: Any) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    if "$game$" in encoded:
        raise ValueError("payload contains the SQL delimiter")
    return encoded


def build_migration_sql(path: Path) -> str:
    games = load_requested_games(path)
    if not games:
        raise ValueError("no pending games to seed")

    submission_values = ",\n".join(
        "      ("
        f"'{game['submissionId']}'::uuid, v_admin_id, "
        f"$game${_json(game['publicGame'])}$game$::jsonb, 'PENDING', 'PUBLIC'"
        ")"
        for game in games
    )
    audit_values = ",\n".join(
        f"      ('{game['submissionId']}'::uuid)"
        for game in games
    )

    return f"""-- Generated by scripts/build_requested_community_games.py. Do not edit by hand.
do $$
declare
  v_admin_id uuid;
  v_admin_count integer;
begin
  select count(*) into v_admin_count from public.admin_users;
  if v_admin_count <> 1 then
    raise exception 'Expected exactly one BoardLog administrator, found %', v_admin_count;
  end if;
  select user_id into strict v_admin_id from public.admin_users;

  insert into public.game_submissions (
    id, owner_user_id, public_game, status, visibility
  )
  values
{submission_values}
  on conflict (id) do nothing;

  insert into public.moderation_events (
    submission_id, owner_user_id, actor_user_id, action, detail
  )
  select seeded.id, v_admin_id, v_admin_id, 'SUBMITTED',
         jsonb_build_object('source', 'requested-community-games-2026-08-18')
  from (values
{audit_values}
  ) as seeded(id)
  where exists (
    select 1 from public.game_submissions submission where submission.id = seeded.id
  )
  and not exists (
    select 1
    from public.moderation_events event
    where event.submission_id = seeded.id and event.action = 'SUBMITTED'
  );
end
$$;
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixture", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(build_migration_sql(args.fixture), encoding="utf-8")
    print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
