-- Generated by scripts/build_requested_community_games.py. Do not edit by hand.
do $$
declare
  v_admin_id uuid;
  v_admin_count integer;
begin
  select count(*) into v_admin_count from public.admin_users;
  if v_admin_count <> 1 then
    raise exception 'Expected exactly one BoardLog administrator, found %', v_admin_count;
  end if;
  select user_id into strict v_admin_id from public.admin_users;

  insert into public.game_submissions (
    id, owner_user_id, public_game, status, visibility
  )
  values
      ('89fb49f6-13ed-5bf2-937c-d7e890cb746e'::uuid, v_admin_id, $game${"aliases":["Mahe","Mahé"],"bggId":3383,"englishName":"Mahé","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":7,"minPlayMinutes":20,"minPlayers":2,"name":"마헤","sourceUrls":["https://boardgamegeek.com/boardgame/3383/mahe"],"tags":["FAMILY","DICE"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('4f7b0785-8ff0-5823-aef6-dddc20eec6c9'::uuid, v_admin_id, $game${"aliases":["셋","세트"],"bggId":1198,"englishName":"SET","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":20,"minPlayMinutes":30,"minPlayers":1,"name":"SET","sourceUrls":["https://boardgamegeek.com/boardgame/1198/set"],"tags":["FAMILY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('665d0b91-c167-5435-b18e-9433401d5c25'::uuid, v_admin_id, $game${"aliases":["노터치 크라켄 디럭스","Don't Mess with Cthulhu Deluxe"],"bggId":253786,"englishName":"Don't Mess with Cthulhu Deluxe","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":8,"minPlayMinutes":1,"minPlayers":4,"name":"노 터치 크라켄 디럭스","sourceUrls":["https://popcorngames.tistory.com/40","https://boardgamegeek.com/boardgame/253786/dont-mess-cthulhu-deluxe"],"tags":["SOCIAL_DEDUCTION","BLUFFING","TEAM","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('b0389bd6-02f7-5e15-a2fa-d2196ea5b1a5'::uuid, v_admin_id, $game${"aliases":["[머미] 우물에 깃든 소리","머미 우물에 깃든 소리"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":4,"minPlayMinutes":120,"minPlayers":4,"name":"우물에 깃든 소리","sourceUrls":["https://murmylab.com/scenarios/67b209c2-4f74-e8f5-c6c3-2ea400000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('f9fe2f51-f7e8-50da-b3a6-71d016a2be0f'::uuid, v_admin_id, $game${"aliases":["[머미] 그날이 오면","머미 그날이 오면"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":4,"minPlayMinutes":120,"minPlayers":4,"name":"그날이 오면","sourceUrls":["https://murmylab.com/scenarios/67b209c2-4f74-e8f5-c6c3-2ea500000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('fb79f97e-15f3-5adb-83e1-34e8ab9827e2'::uuid, v_admin_id, $game${"aliases":["타코캣고트치즈피자","Taco Cat Goat Cheese Pizza"],"bggId":253664,"englishName":"Taco Cat Goat Cheese Pizza","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":8,"minPlayMinutes":10,"minPlayers":2,"name":"타코 캣 고트 치즈 피자","sourceUrls":["https://boardgamegeek.com/boardgame/253664/taco-cat-goat-cheese-pizza"],"tags":["PARTY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('01b83a0b-4e01-5278-910e-5d6addb0fdc4'::uuid, v_admin_id, $game${"aliases":["[머미] 스쿨드","스쿨드","머미 스쿨드"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":4,"minPlayMinutes":120,"minPlayers":4,"name":"스쿨드: 운명의 실타래","sourceUrls":["https://murmylab.com/scenarios/66f1ff5f-7f12-aa6f-cc77-6fb500000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('e3893bc5-627a-5a00-a4c4-aa92dc053f30'::uuid, v_admin_id, $game${"aliases":["[머미] 베르단디","베르단디","머미 베르단디"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":4,"minPlayMinutes":120,"minPlayers":4,"name":"베르단디: 사건의 서막","sourceUrls":["https://murmylab.com/scenarios/66f1ff5f-7f12-aa6f-cc77-6fb400000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('5d565ce5-f951-58c7-955a-6f774726230e'::uuid, v_admin_id, $game${"aliases":["[머미] 우르드","우르드","머미 우르드"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":4,"minPlayMinutes":120,"minPlayers":4,"name":"우르드: 여정의 끝","sourceUrls":["https://murmylab.com/scenarios/66f1ff5f-7f12-aa6f-cc77-6fb600000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('d559e2c7-f8d2-5a6c-937b-062e0cf5ec71'::uuid, v_admin_id, $game${"aliases":["[머미] 레드 X 리그렛","레드 X 리그렛","레드 리그렛"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":5,"minPlayMinutes":120,"minPlayers":5,"name":"레드x리그렛","sourceUrls":["https://murmylab.com/scenarios/687dfa95-0cf7-04bc-e465-dc2300000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('4a5ac43b-af10-55db-ab7c-835e8cbcbef0'::uuid, v_admin_id, $game${"aliases":["Miams"],"englishName":"Miams","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":5,"minPlayMinutes":30,"minPlayers":1,"name":"냠냠냠","sourceUrls":["https://boardm.co.kr/product/detail.html?product_no=7780"],"tags":["FAMILY","DICE","ENGINE_BUILDING"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('c018d29c-2709-57a9-89db-88dbfb98cb69'::uuid, v_admin_id, $game${"aliases":["[머미] 햇살고아원","햇살고아원","머미 햇살고아원"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":6,"minPlayMinutes":120,"minPlayers":6,"name":"햇살고아원: 여섯 아이의 탈출극","sourceUrls":["https://murmylab.com/scenarios/66f2b821-abbd-6df4-d6a8-4f7a00000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('d6d07d05-a70d-5c44-9eab-1b039b716ee3'::uuid, v_admin_id, $game${"aliases":["할리우드","Hollywood 1947"],"englishName":"Hollywood 1947","entryType":"BASE_GAME","maxPlayMinutes":40,"maxPlayers":9,"minPlayMinutes":20,"minPlayers":1,"name":"할리우드 1947","sourceUrls":["https://luckyduckgames.com/france/game/726-dark-cities-hollywood-1947"],"tags":["SOCIAL_DEDUCTION","BLUFFING","TEAM"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('f1ce6226-e196-5a66-8271-71299b9464f2'::uuid, v_admin_id, $game${"aliases":["숲 속의 음악대"],"entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":6,"minPlayMinutes":15,"minPlayers":3,"name":"숲속의 음악대","sourceUrls":["https://room708.tistory.com/103"],"tags":["PARTY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('6fc00721-efaa-5ee0-ad92-1f1ccd45a92e'::uuid, v_admin_id, $game${"aliases":["페이퍼사파리 피카츄와친구들","Paper Safari Pikachu and Friends"],"englishName":"Paper Safari: Pikachu and Friends","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":5,"minPlayMinutes":20,"minPlayers":2,"name":"페이퍼 사파리: 피카츄와 친구들","sourceUrls":["https://www.youtube.com/watch?v=D5-6aNiBngg"],"tags":["FAMILY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('e74259fd-e73b-5446-937b-881c7c4ff537'::uuid, v_admin_id, $game${"aliases":["사운즈 피시","사운즈 피쉬"],"bggId":359893,"englishName":"Sounds Fishy","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":10,"minPlayMinutes":30,"minPlayers":4,"name":"Sounds Fishy","sourceUrls":["https://bigpotato.com/products/sounds-fishy","https://boardgamegeek.com/boardgame/359893/sounds-fishy"],"tags":["PARTY","BLUFFING"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('758b6a12-ae72-56bd-bd54-3fae200f8777'::uuid, v_admin_id, $game${"aliases":["Bosk"],"bggId":252556,"englishName":"Bosk","entryType":"BASE_GAME","maxPlayMinutes":40,"maxPlayers":4,"minPlayMinutes":20,"minPlayers":2,"name":"보스크","sourceUrls":["https://floodgate.games/products/bosk","https://boardgamegeek.com/boardgame/252556/bosk"],"tags":["STRATEGY","FAMILY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('579efbad-d788-59c3-8c3b-7ffa6c9d45f1'::uuid, v_admin_id, $game${"aliases":["피기옐로우","Piggy Yellow"],"englishName":"Piggy Yellow","entryType":"BASE_GAME","maxPlayMinutes":15,"maxPlayers":8,"minPlayMinutes":15,"minPlayers":2,"name":"피기 옐로우","sourceUrls":["https://www.gaminglib.com/products/piggy-yellow"],"tags":["FAMILY","COOPERATIVE","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('22cb19cf-a928-5bb1-b666-bade562dd3c9'::uuid, v_admin_id, $game${"aliases":["Botswana"],"bggId":398,"englishName":"Botswana","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":5,"minPlayMinutes":20,"minPlayers":2,"name":"보츠와나","sourceUrls":["https://boardm.co.kr/product/detail.html?product_no=7803","https://boardgamegeek.com/boardgame/398/botswana"],"tags":["FAMILY","CARD","ECONOMIC"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('8395378b-df86-5dce-ae7c-1d4de3a1a6aa'::uuid, v_admin_id, $game${"aliases":["플립7","Flip 7"],"bggId":420087,"englishName":"Flip 7","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":18,"minPlayMinutes":20,"minPlayers":3,"name":"플립 7","sourceUrls":["https://boardgamegeek.com/boardgame/420087/flip-7"],"tags":["PARTY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('edaa09d4-7c54-5d4d-b07a-f068598d99d4'::uuid, v_admin_id, $game${"aliases":["Coyote"],"englishName":"Coyote","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":10,"minPlayMinutes":20,"minPlayers":3,"name":"코요테","sourceUrls":["https://www.wingboardgame.com/2024/08/blog-post_30.html"],"tags":["PARTY","BLUFFING","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('46bef9da-6eff-573b-9564-5a8fe2cef549'::uuid, v_admin_id, $game${"aliases":["[머미] 새장 속 제비는 꿈을 꾼다","머미 새장 속 제비는 꿈을 꾼다"],"entryType":"BASE_GAME","maxPlayMinutes":180,"maxPlayers":9,"minPlayMinutes":180,"minPlayers":7,"name":"새장 속 제비는 꿈을 꾼다","sourceUrls":["https://murmylab.com/scenarios/66f3ceef-cc91-6ba9-c453-6b8900000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('58a5faf7-1c7c-58a1-9730-d911e932bc4c'::uuid, v_admin_id, $game${"aliases":["후지플러시","Fuji Flush"],"bggId":203430,"englishName":"Fuji Flush","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":8,"minPlayMinutes":10,"minPlayers":3,"name":"후지 플러시","sourceUrls":["https://boardgamegeek.com/boardgame/203430/fuji-flush"],"tags":["FAMILY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('87d3b00f-c4b8-545d-b75b-957f87137dc5'::uuid, v_admin_id, $game${"aliases":["해녀","해녀 확장판","Haenyeo","Sea Divers of Jeju"],"englishName":"Haenyeo: Sea Divers of Jeju","entryType":"BASE_GAME","maxPlayMinutes":40,"maxPlayers":5,"minPlayMinutes":20,"minPlayers":2,"name":"해녀: Sea Divers of Jeju","sourceUrls":["https://gamemarket.jp/game/188177"],"tags":["FAMILY","ECONOMIC","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('4eb0b772-a591-5e1c-9ab3-3b26c9c6f5b1'::uuid, v_admin_id, $game${"aliases":["[머미] 양심의 기생","머미 양심의 기생"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":3,"minPlayMinutes":120,"minPlayers":3,"name":"양심의 기생","sourceUrls":["https://murmylab.com/scenarios/6759bba6-19ed-77da-51b0-d20300000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('534aec04-9b35-5abe-8697-1505822d6ccc'::uuid, v_admin_id, $game${"aliases":["[머미] 다크율에 속죄를","다크율에 속죄를","머미 다크율에 속죄를"],"entryType":"BASE_GAME","maxPlayMinutes":180,"maxPlayers":9,"minPlayMinutes":180,"minPlayers":7,"name":"다크 율에 속죄를","sourceUrls":["https://murmylab.com/scenarios/682800c8-06c6-b423-ac5d-788000000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('d1106797-c975-5569-8ceb-d62f6d86f0bd'::uuid, v_admin_id, $game${"aliases":["[머미] 게놈의 탑","머미 게놈의 탑"],"entryType":"BASE_GAME","maxPlayMinutes":180,"maxPlayers":7,"minPlayMinutes":180,"minPlayers":7,"name":"게놈의 탑","sourceUrls":["https://murmylab.com/scenarios/682800c8-06c6-b423-ac5d-788100000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('437b6c7e-c4cb-5fd4-864e-9e8022d7a625'::uuid, v_admin_id, $game${"aliases":["[머미] 탐욕의 저택","탐욕의 저택","머미 탐욕의 저택"],"entryType":"BASE_GAME","maxPlayMinutes":150,"maxPlayers":4,"minPlayMinutes":150,"minPlayers":4,"name":"탐욕 PART.01 탐욕의 저택","sourceUrls":["https://murmylab.com/scenarios/68934b09-70d5-8724-3eb3-8dd000000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('4802b25e-90d7-5439-a586-46c25b116f2b'::uuid, v_admin_id, $game${"aliases":["For a Crown"],"bggId":431248,"englishName":"For a Crown","entryType":"BASE_GAME","maxPlayMinutes":45,"maxPlayers":5,"minPlayMinutes":30,"minPlayers":3,"name":"가문의 왕관","sourceUrls":["https://boardgamegeek.com/boardgame/431248/for-a-crown","https://m.yes24.com/goods/detail/146742377"],"tags":["FAMILY","NEGOTIATION","DECK_BUILDING"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('8d7f81bb-e385-5364-ab6e-3127923b14fd'::uuid, v_admin_id, $game${"aliases":["피나콜라다이스","Pina Coladice","Piña Coladice"],"bggId":415054,"englishName":"Piña Coladice","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":4,"minPlayMinutes":10,"minPlayers":2,"name":"피나 콜라다이스","sourceUrls":["https://boardgamegeek.com/boardgame/415054/pina-coladice"],"tags":["FAMILY","DICE"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('9e76257e-42ca-586e-bd6a-79b660d797db'::uuid, v_admin_id, $game${"aliases":["Batam"],"englishName":"Batam","entryType":"BASE_GAME","maxPlayMinutes":45,"maxPlayers":4,"minPlayMinutes":45,"minPlayers":3,"name":"바탐","sourceUrls":["https://www.playte.com/"],"tags":["STRATEGY","ECONOMIC"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('b1ee03cc-6a48-51d3-877c-5b75100c2b04'::uuid, v_admin_id, $game${"aliases":["[머미] J. 모리아티의 암약","J 모리아티의 암약","머미 J 모리아티의 암약"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":4,"minPlayMinutes":120,"minPlayers":4,"name":"J.모리아티의 암약","sourceUrls":["https://murmylab.com/scenarios/66f55cea-1089-785d-725f-959000000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('68d571a1-78ad-5afa-b33c-d46054b74087'::uuid, v_admin_id, $game${"aliases":["[머미] 절벽산장 살인사건","머미 절벽산장 살인사건"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":5,"minPlayMinutes":120,"minPlayers":4,"name":"절벽산장 살인사건","sourceUrls":["https://murmylab.com/scenarios/68e7c49d-a0e0-d9a3-7928-fc5d00000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('df215a57-a9ea-541a-a7e3-2c4be4a68ef9'::uuid, v_admin_id, $game${"aliases":["[머미] 셜록: 주홍색 연구","셜록 주홍색 연구","주홍색 연구"],"englishName":"Sherlock Part. 01: A Study in Scarlet","entryType":"BASE_GAME","maxPlayMinutes":90,"maxPlayers":5,"minPlayMinutes":90,"minPlayers":3,"name":"셜록 Part.01 주홍색 연구","sourceUrls":["https://www.wadiz.kr/web/campaign/detail/401704","https://www.mamumi.site/game-list"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('4ec38c68-1595-5fdd-ae29-1e9b64bf35f8'::uuid, v_admin_id, $game${"aliases":["[머미] 사라진 속옷과 하늘을 나는 물고기","머미 사라진 속옷과 하늘을 나는 물고기"],"entryType":"BASE_GAME","maxPlayMinutes":60,"maxPlayers":5,"minPlayMinutes":60,"minPlayers":5,"name":"사라진 속옷과 하늘을 나는 물고기","sourceUrls":["https://murmylab.com/scenarios/672327b9-728a-89b8-d76d-30d700000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('84d927c7-be69-5db1-a94c-4d470fa78628'::uuid, v_admin_id, $game${"aliases":["[머미] 무령","머미 무령"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":5,"minPlayMinutes":120,"minPlayers":4,"name":"무령","sourceUrls":["https://murmylab.com/scenarios/66fa6c04-e195-6ae6-7883-6f7300000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('92d51cb4-0777-5649-953c-62a07bab455a'::uuid, v_admin_id, $game${"aliases":["Play Jeju"],"englishName":"Play Jeju","entryType":"BASE_GAME","maxPlayMinutes":30,"maxPlayers":4,"minPlayMinutes":30,"minPlayers":2,"name":"플레이 제주","sourceUrls":["https://prod.danawa.com/info/?pcode=3418945"],"tags":["FAMILY","TILE_PLACEMENT"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('c6a1cc55-d059-5a21-80b8-026d1743b24a'::uuid, v_admin_id, $game${"aliases":["Carnival of Sins"],"englishName":"Carnival of Sins","entryType":"BASE_GAME","maxPlayMinutes":20,"maxPlayers":5,"minPlayMinutes":15,"minPlayers":2,"name":"죄악의 카니발","sourceUrls":["https://tranjisgames.com/shop/trg-117car-carnival-of-sins-2218"],"tags":["PARTY","DICE","BLUFFING"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('c1f1e2c6-25ff-5fa9-a73d-25eb6dbf2625'::uuid, v_admin_id, $game${"aliases":["바보타임","Fou Fou Fou!"],"englishName":"Fou Fou Fou!","entryType":"BASE_GAME","maxPlayMinutes":15,"maxPlayers":8,"minPlayMinutes":15,"minPlayers":3,"name":"바보 타임","sourceUrls":["https://boardlife.co.kr/game/16973"],"tags":["PARTY","CARD"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('0c1d7ba3-4b05-521b-9eed-50f55639dc59'::uuid, v_admin_id, $game${"aliases":["[머미] 껍질 속 세상","껍질속세상","머미 껍질 속 세상"],"entryType":"BASE_GAME","maxPlayMinutes":180,"maxPlayers":8,"minPlayMinutes":180,"minPlayers":7,"name":"껍질 속 세상","sourceUrls":["https://murmylab.com/scenarios/66f3eb76-cc91-6ba9-c453-6bf000000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC'),
      ('2c64d899-e2cc-5ebd-892d-7c08095de448'::uuid, v_admin_id, $game${"aliases":["[머미] 지구에서 사랑을 담아","머미 지구에서 사랑을 담아"],"entryType":"BASE_GAME","maxPlayMinutes":120,"maxPlayers":7,"minPlayMinutes":120,"minPlayers":7,"name":"지구에서 사랑을 담아","sourceUrls":["https://murmylab.com/scenarios/6811ae3c-edc0-bfb2-fe16-bb2000000000"],"tags":["DEDUCTION","MURDER_MYSTERY"]}$game$::jsonb, 'PENDING', 'PUBLIC')
  on conflict (id) do nothing;

  insert into public.moderation_events (
    submission_id, owner_user_id, actor_user_id, action, detail
  )
  select seeded.id, v_admin_id, v_admin_id, 'SUBMITTED',
         jsonb_build_object('source', 'requested-community-games-2026-08-18')
  from (values
      ('89fb49f6-13ed-5bf2-937c-d7e890cb746e'::uuid),
      ('4f7b0785-8ff0-5823-aef6-dddc20eec6c9'::uuid),
      ('665d0b91-c167-5435-b18e-9433401d5c25'::uuid),
      ('b0389bd6-02f7-5e15-a2fa-d2196ea5b1a5'::uuid),
      ('f9fe2f51-f7e8-50da-b3a6-71d016a2be0f'::uuid),
      ('fb79f97e-15f3-5adb-83e1-34e8ab9827e2'::uuid),
      ('01b83a0b-4e01-5278-910e-5d6addb0fdc4'::uuid),
      ('e3893bc5-627a-5a00-a4c4-aa92dc053f30'::uuid),
      ('5d565ce5-f951-58c7-955a-6f774726230e'::uuid),
      ('d559e2c7-f8d2-5a6c-937b-062e0cf5ec71'::uuid),
      ('4a5ac43b-af10-55db-ab7c-835e8cbcbef0'::uuid),
      ('c018d29c-2709-57a9-89db-88dbfb98cb69'::uuid),
      ('d6d07d05-a70d-5c44-9eab-1b039b716ee3'::uuid),
      ('f1ce6226-e196-5a66-8271-71299b9464f2'::uuid),
      ('6fc00721-efaa-5ee0-ad92-1f1ccd45a92e'::uuid),
      ('e74259fd-e73b-5446-937b-881c7c4ff537'::uuid),
      ('758b6a12-ae72-56bd-bd54-3fae200f8777'::uuid),
      ('579efbad-d788-59c3-8c3b-7ffa6c9d45f1'::uuid),
      ('22cb19cf-a928-5bb1-b666-bade562dd3c9'::uuid),
      ('8395378b-df86-5dce-ae7c-1d4de3a1a6aa'::uuid),
      ('edaa09d4-7c54-5d4d-b07a-f068598d99d4'::uuid),
      ('46bef9da-6eff-573b-9564-5a8fe2cef549'::uuid),
      ('58a5faf7-1c7c-58a1-9730-d911e932bc4c'::uuid),
      ('87d3b00f-c4b8-545d-b75b-957f87137dc5'::uuid),
      ('4eb0b772-a591-5e1c-9ab3-3b26c9c6f5b1'::uuid),
      ('534aec04-9b35-5abe-8697-1505822d6ccc'::uuid),
      ('d1106797-c975-5569-8ceb-d62f6d86f0bd'::uuid),
      ('437b6c7e-c4cb-5fd4-864e-9e8022d7a625'::uuid),
      ('4802b25e-90d7-5439-a586-46c25b116f2b'::uuid),
      ('8d7f81bb-e385-5364-ab6e-3127923b14fd'::uuid),
      ('9e76257e-42ca-586e-bd6a-79b660d797db'::uuid),
      ('b1ee03cc-6a48-51d3-877c-5b75100c2b04'::uuid),
      ('68d571a1-78ad-5afa-b33c-d46054b74087'::uuid),
      ('df215a57-a9ea-541a-a7e3-2c4be4a68ef9'::uuid),
      ('4ec38c68-1595-5fdd-ae29-1e9b64bf35f8'::uuid),
      ('84d927c7-be69-5db1-a94c-4d470fa78628'::uuid),
      ('92d51cb4-0777-5649-953c-62a07bab455a'::uuid),
      ('c6a1cc55-d059-5a21-80b8-026d1743b24a'::uuid),
      ('c1f1e2c6-25ff-5fa9-a73d-25eb6dbf2625'::uuid),
      ('0c1d7ba3-4b05-521b-9eed-50f55639dc59'::uuid),
      ('2c64d899-e2cc-5ebd-892d-7c08095de448'::uuid)
  ) as seeded(id)
  where exists (
    select 1 from public.game_submissions submission where submission.id = seeded.id
  )
  and not exists (
    select 1
    from public.moderation_events event
    where event.submission_id = seeded.id and event.action = 'SUBMITTED'
  );
end
$$;
